### PR TITLE
Problem solved for the case where xmin=0 in home-button.js

### PR DESCRIPTION
**Pull request by KevCaz**
Hi @tim-salabim,

This PR solves the issue described in mapview https://github.com/r-spatial/mapview/issues/360. Here is a better reprex using `leaflet` and `leafem` :

```{R}
library(leaflet)
m <- leaflet() %>% 
   addProviderTiles("OpenStreetMap") %>% 
   addCircleMarkers(data = breweries91, group = "breweries91") %>% 
   addHomeButton(ext = c(0, 10, 0, 10), group = "Brew")  
m
```

The problem is caused by the following test

https://github.com/r-spatial/leafem/blob/9db681e08fec7d8801f4c299c56eb661d6fefb9b/inst/htmlwidgets/lib/HomeButton/home-button.js#L9-L13

When `xmin` is actually 0 (very unlikely with real data, more likely with made ones!) and `group` is not properly defined, then the extent is not properly set-up. As this all happens in the JS scipt, this goes under quietly. The PR solves this issue in a first commit by adding one variable to explicit use the extent when relevant. With this commit, the example above works fine and (and so does the problem I reported in mapview). I added a second commit to fix 2 warnings due to missing dependencies in the `IMPORT` field.

Again thanks for your work on `mapview` and `leafem`.

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks! And sorry for me taking so long to merge...

**Comment by KevCaz** [comment]
@tim-salabim, I would be very happy to be added as contributor, thanks for the opportunity! I'm using leafem frequently (via mapview) and would be happy to help whenever I'll be able to. If this is ok with you that's what I would use in `DESCRIPTION`: 

```
person(given = "Kevin",  
  family = "Cazelles", 
  role = "ctb",
  email = "kevin.cazelles@gmail.com", 
  comment = c(ORCID = "0000-0001-6619-9874"))
```

Looks like nobody is using the ORCID here, so please feel free to drop it if you think it's not necessary.

**Comment by tim-salabim** [comment]
Done! Again, thanks for the contribution!

**Comment by KevCaz** [comment]
Thanks!

**Pull request merged**
