### PR TITLE
Hide addImageQuery legend if empty/not visible

### PR DESCRIPTION
**Pull request by trafficonese**
When the map initializes, the legend control will be visible, but as soon as you hover over the map, they should disappear when no values are found or when the layer is hidden.

I also added the `className` argument to `addImageQuery`, so one can add his own CSS-class to the legend controls.

I also cleaned up joda.js a bit. There were still some leftovers from my previous attempt to display multiple values.

Here's a little example, using the `className`. 

```
library(leaflet)
library(leafem)
library(plainview)
library(shiny)  

style <- HTML(".myownlegendcss {
    margin: 0 !important;
    border-radius: 0;
    border: 0;
    box-shadow: 0 0 0;
}")

ui <- fluidPage(
  tags$head(tags$style(style)),
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("OpenStreetMap") %>%
      addRasterImage(poppendorf[[1]], project = TRUE, group = "poppendorf1",
                     layerId = "poppendorf1") %>%
      addImageQuery(poppendorf[[1]], project = TRUE,
                    layerId = "poppendorf1", className = "myownlegendcss") %>%
      addRasterImage(poppendorf[[4]], project = TRUE, group = "poppendorf2",
                     layerId = "poppendorf2") %>%
      addImageQuery(poppendorf[[4]], project = TRUE,
                    layerId = "poppendorf2", className = "myownlegendcss") %>%
      addLayersControl(overlayGroups = c("poppendorf1", "poppendorf2"))
  })
}
shinyApp(ui, server)
```

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks! This should be much more usable now! Btw, I saw your **leaflet.extras2** the other day. I think your opening up a few options for mapview there... I'd love to get rid of some of the clutter in mapview regarding legends, homebuttons etc. Do you think that leaflet.sidebar-v2 could be a place for those?

**Comment by trafficonese** [comment]
I'm not sure I understand it correctly. Would you like to export all the legends/homebuttons to leaflet.extras2 or include it in a standard sidebar? I thought most of the "clutter" is already exported to `leafem`?

I would like to add 2-3 plugins more, extend some of the current ones and I am already seeing check-Notes that the package is above 5Mb. I can still shrink it, since the examples are already around 1Mb and the JS-sources are not minified yet. At the moment, however, I don't know how much space will be left.

What about a new package `mapview.extras` ?

**Comment by tim-salabim** [comment]
Sorry, I wasn't very clear, I realise now that I re-read my comment. 

What I was trying to say is that I'd love to utilise leaflet.sidebar-v2 to house different parts of the mapview map, such as  the legends, homebuttons - ideally these would be integrated with the title of the legends so that clicking on those would zoom to the layer. There are many more thoughts like this in my head (e.g. having opacity sliders for the layers) but the space on the map widget is limited, hence the thought of generating a dedicated mapview sidebar where things could be conveniently arranged...

Is this more clear?

**Comment by trafficonese** [comment]
Sry for the late reply, I lost this thread :)

Yes, I guess the sidebar could be an option for some of these controls, but it is restricted to Shiny-Apps or maybe markdown (hasnt been tested yet), as the sidebar-HTML has to be created before the `leafletOutput()`. And I am also not too sure about legends, unless you can insert them in a `uiOutput()`.

However, you can try the [sidebar-example](https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/sidebar_app.R) and check if you see any potential for `mapview`.

**Pull request merged**
