### PR TITLE
utils - getProjection

### PR DESCRIPTION
**Pull request by cstepper**
Hi Tim,

looks like I encountered the new sf crs before you found some time to fix it here.
Just fixed it here in order to render a mapview :)

Cheers, Christoph

### CODE REVIEW

**Comment by tim-salabim** [comment]
Hm... Thanks!
This would break with old **sf** releases though, wouldn't it?

For mapview @edzer had no problems with
https://github.com/r-spatial/mapview/blob/develop/R/mapviewControls.R#L191-L201

So I'm wondering which is the best way forward. Given that **leafem** needs a hotfix release yesterday, I'll probably stick with the `$proj4string` for now. Switching to `wkt` completely needs a little more thinking especially in `addMouseCoordinates`.

**Comment by edzer** [comment]
It all depends on what is going to happen with this string, and to what extent it can describe the CRS.

**Comment by tim-salabim** [comment]
Thanks for the input @edzer ! For the current CRAN version of sf this should be ok though, right? Another thing that is important here is also how **raster** is going to change. For mapview, it would be best if all (relevant) spatial classes return similar objects so that we can compare across the borad.

**Comment by tim-salabim** [comment]
@cstepper I manually added the one-liner. Seems cleaner that merging all the commits above. Thanks for bringing it to my attention though!!

**Pull request closed without merging**
