### PR TITLE
Randomize data dependency name

### LINKED ISSUE #17: Shiny: ImageQuery doesn't update itself in new leaflet map
Hi I came across this issue #15 when troubleshoot my current issue with ImageQuery; thought I'll give this a try and see if this is a feature problem or that I should seek for workaround. My Shiny app starts out displaying a RasterLayer and the user can "update" the RasterLayer by, say moving the slider left or right. In my Shiny code, since I use renderLeaflet, my idea is that everytime user move the slider, a new leaflet map is created with the raster values updated. However, the ImageQuery doesn't update according to this new raster and leaflet map. Here's a simplified example of the problem:

```
library(leaflet)
library(plainview)
library(leafem)
library(shiny)

ras <- poppendorf[[1]]

ui <- fluidPage(
  fluidRow(
    sliderInput("factor", "Factor for raster values",
                min = 0.5, max = 2, value = 1),
    leafletOutput("map")
  )
)

server <- function(input, output) {
  output$map <- renderLeaflet({
    ras1 <- ras * input$factor
    
    leaflet() %>%
      addRasterImage(ras1, project = TRUE, group = "poppendorf",
                     layerId = "poppendorf") %>%
      addImageQuery(ras1, project = TRUE,
                    layerId = "poppendorf",position="bottomleft",prefix = "") %>%
      addLayersControl(overlayGroups = "poppendorf")
    
  })
}

shinyApp(ui, server)
```

The shiny app starts out with a leaflet map with raster. Mouseover shows the values are around 9000 something. Now when I slide to factor of 2, the raster values would be updated to 18000 something. However, when mouseover the layer, those values remain at 9000 something. It seems like ImageQuery retains its memory even if a new leaflet map is created and a new raster is used. Is this an expected behaviour? Am I doing my leaflet right? (I'm relatively new to this...)

Thanks!

Ben

### PR DESCRIPTION
**Pull request by trafficonese**
This would fix #17

Since there cannot be multiple html-dependencies with the same name, updating the raster/imagequery did not work because  the first uploaded data dependency was always queried.

It seems that the dependency name doesn't really matter to the function, so I "randomized" the name.
I also removed the script tags from the head section. This isn't really necessary, and there is probably a better way of doing it.

@tim-salabim, @kokbent Would you mind giving it a try to see if everything still works as expected?

PS: I also tried to implement a `removeImageQuery`, which succesfully deletes the `InfoLegend` and the `window.data` object, but I didnt manage to remove the `on` event for that single layer, since it is bound to the map. So after removing an imageQuery, the console would be full of this message:

> leafem: Failed to find data arrays for layerId ...

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks @trafficonese for all your efforts! I am holding off on this, as I likely will not pursue the `leaflet::addRasterImage` road anymore, but rather expand the functionality of `leafem::addGeotiff/addGeoraster` for displaying raster data. See this demo for a queryable raster display (click to get the cell value). 

https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/load-via-script-tag-with-geoblaze.html

That said, we should probably still provide a working `addImageQuery` for others wanting to use `addRasterImage`...

**Comment by kokbent** [comment]
Awesome! Will test it out as soon as I have some free time!

**Comment by kokbent** [comment]
I can confirm that #17 problem is fixed in this branch, ImageQuery updates properly when you create new leaflet map with same layerId. This is super awesome and thank you very much @trafficonese !

**Comment by DEQygrund** [comment]
@kokbent and @tim-salabim Could you please take a look at my codes? The addImageQuery still doesn't work on leafletProxy for me. 
`       rst <- reactive({raster::raster(paste0(map.tif.dir(),file.name()))}) 
        
        lid <- paste0("Value",input$date_map)

        leafletProxy("map") %>% 
          leaflet::clearImages() %>% 
          leaflet::clearControls() %>% 
          leaflet::addRasterImage(rst(), layerId = lid, project = TRUE, colors=pal.map, opacity = 1) %>% 
          #leafem::addMouseCoordinates() %>% 
          leafem::addImageQuery(rst(), layerId = lid, project = TRUE, type = "mousemove",
                                position="topright",prefix = "") %>% 
          leaflet::addLegend(pal = pal.map, values = thevalues, title = "Cyanobacteria (cells/mL)", position = "topright",
                             labFormat = function(type,cuts,p){paste0(labels)}) %>% 
          leaflet::addLayersControl(#overlayGroups = c("Hydrologic Unit 8 (HU8)","Land Cover (NLCD 2016)","Value"),
                                    overlayGroups = lid,
                                    baseGroups = c("OpenStreetMap","National Geographic World Map"),
                                    position = "topleft",
                                    options = layersControlOptions(collapsed = TRUE, autoZIndex = FALSE)) `

**Pull request merged**
