### PR TITLE
Layerviewcontrol

### LINKED ISSUE #90: Adjust setView() for each group
Perhaps this feature could be considered as an extension within leafem?
https://github.com/rstudio/leaflet/issues/931

### PR DESCRIPTION
**Pull request by trafficonese**
fixes #90 

I didn't add the legend part, I tried a bit but it's painful. And I never add feature layers as basegroup, so it didn't seem a high priority for me.

I also added a shiny example in `/inst/test_layerviewcontrol.R`

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks, this is awesome!
* How do you feel about providing an enhanced version of `leaflet::addLayersControl()` with default behaviour just calling the standard generic? I.e. overriding `leaflet::addLayersControl` with `leafem::addLayersControl` when leafem is loaded...
* For the overlay layers, is it possible to separate the view change logic between show/hide and the home_btn? IMHO the view shouldn't change (by default) when I activate/show an overlay layer, as I might want to simply show/hide with a fixed view to see what changes (especially when I have dedicated buttons for zooming to the layer)

**Comment by trafficonese** [comment]
I would prefer to keep the 2 functions separate or I dont see the advantage of mixing them.

Yes that is definitly possible.

**Comment by trafficonese** [comment]
new argument `setviewonselect`, which is TRUE by default - so it will zoom on the layer if selected

**Comment by tim-salabim** [comment]
> I would prefer to keep the 2 functions separate or I dont see the advantage of mixing them.

As it stands currently, `addLayerViewControl` will not work without a `addLayersControl` call. So, either we enhance the latter or we would need to change the name, so that it becomes obvious that one is not adding something, but rather updating the existing layers control. `updateLayersControl` already exists though...

**Comment by tim-salabim** [comment]
BTW, I am also contemplating adding options for opacity sliders and color legends. This would make things much cleaner than the current legend solutions that are available...

**Comment by trafficonese** [comment]
I see, you're right. I will look into it.

You mean to inlcude one of those opacity plugins to change the opacity of base and overlay groups, or add a custom JS function?
https://github.com/lizardtechblog/Leaflet.OpacityControls
https://github.com/dayjournal/Leaflet.Control.Opacity
https://github.com/Raruto/leaflet-transparency 

And how should the color legend look like? You mean to integrate the whole R-leaflet legend in the layersControl or should it be just 1 colored symbol per group?

**Comment by tim-salabim** [comment]
> You mean to inlcude one of those opacity plugins to change the opacity of base and overlay groups, or add a custom JS function?

Yes, just a simple horizontal slider that does not take too much space. 

> And how should the color legend look like?

Just a standard legend, horizontal placed under the layer name, so you'd have

layername | homebutton
horizontal opacity slider
horizontal color legend

Both opacity slider and legend could/should probably be hidden when the layer is hidden... 

Legends for standard basemaps are not necessary I guess. 

But I can take care of implementing this as soon as we have a working function to extend standard layers control... This is mainly for mapview to make maps look cleaner

**Comment by trafficonese** [comment]
Got it.

We could maybe integrate it in [addGroupedLayersControl](https://trafficonese.github.io/leaflet.extras/reference/addGroupedLayersControl.html)

Right now I think the `layerviewcontrol` should work for both `leaflet::addLayersControl` and `leaflet.extras::addGroupedLayersControl`, but didnt test it.

**Comment by tim-salabim** [comment]
Hm, not a bad idea... I agree that whatever we implement, it should be compatible with both standard and grouped layer control. If I envision all this correctly, then we either need a `extendLayersControl` function that works with both standard and grouped controls or implement a completely new layers control function that integrates all of this into one function (which could be an extended `addGroupedLayersControl` I guess... From my point of view, I'd like to have something in leafem that would satisfy my ideas for mapview, that way I have more control... Just thinking out loud

**Comment by trafficonese** [comment]
I went for `extendLayerControl` and it should be working for normal layercontrols and the grouped version. 🥳 

I am hijacking the legends with a corresponding `layerId`, so the `addLegend` should have both `layerId` and `group` point to the layer group:
`addLegend(..., layerId = "mygroup", group = "mygroup")`

See the [example ](https://github.com/r-spatial/leafem/pull/93/commits/de9deb2036485b04d348290601578f1654bb9ae8)

image

**Comment by tim-salabim** [comment]
Ok, this is fantastic!!! The only small issue I have is that horizontal legends would make it even better :-) Do you think that's possible without too much effort? Package `leaflegend` does have a solution for it...

**Comment by trafficonese** [comment]
Maybe if we overwrite quite some CSS, but it would be best if `addLegend` offered this option.

**Comment by tim-salabim** [comment]
Maybe we can just utilize `leaflegend`? 
https://roh.engineering/posts/2022/07/leaflegend-recipes/

**Comment by trafficonese** [comment]
I thought the exact same, but I will have to test it as `leaflegend` is not using a `layerId`, so the code needs some adapting maybe.

**Comment by trafficonese** [comment]
Gettin there ;)
I just pushed a fix that makes leaflegend work aswell. Full flexibility now 🚀 
image

I just noticed, sometimes the `layerId` needs to be set in leaflegend and sometimes the group was sufficient.

**Comment by tim-salabim** [comment]
@trafficonese is this ready to merge?

**Comment by trafficonese** [comment]
yes I think so, allthough I haven't tested it a lot yet.

**Comment by tim-salabim** [comment]
@trafficonese I just pushed https://github.com/r-spatial/leafem/commit/5cd42e8b150aac19835dcc35e58a98c172bfa227 which renames the function to `customizeLayersControl` as it now allows to change the CSS of the control among other things. The example has been updated to reflect all that is possible now. I am now happy with this (I think) as it allows for all modifications I have in mind for mapview. I hope this is all also ok for you?

**Pull request merged**
