### PR TITLE
fix: fixes #68 accept terra objects in addRasterRGB

### LINKED ISSUE #68: Could addRasterRGB support SpatRaster class object
Hi everyone,

The raster package announced it has been superseded by the "terra" package.
[https://cran.r-project.org/web/packages/raster/index.html](url)

Could addRasterRGB function support object in terra package in future?
Such as SpatRaster created by `terra::rast()` .

Thank you.

### PR DESCRIPTION
**Pull request by trafficonese**
More info in issue #68.

For now I am using the `near` method for reprojecting. 

Should we expose `method` as new argument and use this leaflet logic
https://github.com/trafficonese/leaflet/blob/92bc272caa9a268140e75ede1966bcdc7d585636/R/layers.R#L499-L513 ?

-------------
          

Here's a little Shiny-App as playground:

<details>
  <summary>Click me</summary>

```
library(shiny)  
library(leafem)
library(leaflet)
library(terra)

rasterdf <- plainview::poppendorf
terrradf <- terra::rast(df)

ui <- fluidPage(
  leafletOutput("map", height = 900)
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles(group = "OpenStreetMap") %>%
      addRasterRGB(rasterdf, 4,3,2, group="raster") %>% 
      addRasterRGB(terrradf, 4,3,2, group="terra") %>% 
      addLayersControl(overlayGroups = c("raster","terra"))
  })
}
shinyApp(ui, server)
```

</details>

### CODE REVIEW

**Comment by tim-salabim** [comment]
Thanks! Yes, I think we should expose the `method` argument and handle it equivalently to leaflet.

**Comment by trafficonese** [comment]
I included the `method` argument.

2 other "problems" came up..
- With `terra` objects the data will get **projected twice** currently, also if the data is already in EPSG:3857, as the default value for `addRasterImage` is `project = TRUE`.

- When using a `stars` object in `addRasterRGB` we still get the error in #68 because of different lengths:

> Error in dim(tileData) <- c(4, nrow(projected), ncol(projected)) :
> dims [product 118332] do not match the length of object [110888]

```
library(leafem); library(leaflet); library(stars)
leaflet() %>% addTiles() %>%
  addRasterRGB(st_as_stars(plainview::poppendorf), 4, project = TRUE)
```

**Comment by trafficonese** [comment]
With [8c1987e](https://github.com/r-spatial/leafem/pull/81/commits/8c1987e2d471cd08311f526c04ebf380ffe83543) I now check if the projection is already 3857 and set `project = FALSE` for `terra` objects.

I also changed `apply(mat, 1, anyNA)` with `rowSums(is.na(mat)) > 0`, which should be around 50 times faster. We could further increase the performance with `matrixStats::rowAnyNAs(mat)`, but I think thats fast enough and there is a maximum raster size anyway

> Error in addRasterImage_SpatRaster: Raster image too large; 5725014 bytes is greater than maximum 4194304 bytes

**Comment by tim-salabim** [comment]
Thanks!

**Comment by tim-salabim** [comment]
with https://github.com/r-spatial/leafem/commit/8ab848fd8bc965bd977d1df52d7dae6b7854b9fb reprojecting should now work properly for all 3 classes (raster, terra, stars). I decided to use their native reprojection versions, rather than relying on `leaflet::projectRasterForLeaflet()`

**Pull request merged**
